services:
  api:
    build: .
    image: luminalib-app:latest
    container_name: luminalib-api
    # command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./:/app
    entrypoint: ["sh", "docker/entrypoint.sh"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    depends_on:
      - db
      - redis
      - minio
      - ollama
    ports:
      - "8000:8000"

  worker:
    build: .
    image: luminalib-app:latest
    container_name: luminalib-worker
    volumes:
      - ./:/app
    entrypoint: ["sh", "docker/entrypoint.sh"]
    command: celery -A app.core.celery_app worker --loglevel=info -Q llm,recs,celery
    # command: celery -A app.core.celery_app worker -l info
    env_file: .env
    depends_on:
      - api
      - redis
      - db
      - minio
      - ollama

  beat:
    build: .
    image: luminalib-app:latest
    container_name: luminalib-beat
    volumes:
      - ./:/app
    entrypoint: ["sh", "docker/entrypoint.sh"]
    command: celery -A app.core.celery_app beat --loglevel=info
    # command: celery -A app.core.celery_app beat -l info
    env_file: .env
    depends_on:
      - worker
      - redis

  db:
    image: postgres:17
    container_name: luminalib-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: luminalib
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: luminalib-redis
    ports:
      - "6379:6379"

  minio:
    image: quay.io/minio/minio
    container_name: luminalib-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio-data:/data

  minio-mc:
    image: minio/mc
    container_name: luminalib-minio-mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      for i in $(seq 1 30); do
        mc alias set local http://minio:9000 minioadmin minioadmin && mc mb --ignore-existing local/luminalib && exit 0;
        echo 'waiting for minio...';
        sleep 2;
      done;
      echo 'minio not ready'; exit 1
      "

  ollama:
    image: ollama/ollama:latest
    container_name: luminalib-ollama
    environment:
      OLLAMA_HOST: 0.0.0.0
    volumes:
      - ollama:/root/.ollama
    ports:
      - "11434:11434"

  ollama-pull:
    image: ollama/ollama:latest
    container_name: luminalib-ollama-pull
    depends_on:
      - ollama
    entrypoint: >
      /bin/sh -c "
      /bin/sleep 5 &&
      OLLAMA_HOST=http://ollama:11434 ollama pull mistral
      "

volumes:
  pgdata:
  minio-data:
  ollama:
